import { motion } from 'framer-motion';
import { ArrowRight, ChevronRight, Code2, Menu, Play, Sparkles, X } from 'lucide-react';
import { useState } from 'react';
import Features from './components/Features';
import Templates from './components/Templates';
import Pricing from './components/Pricing';
import Payment from './components/Payment';
import Footer from './components/Footer';
const navItems = [['Features','features'],['Templates','templates'],['Pricing','pricing'],['Demo','demo']];
export default function App(){
 const [mobileOpen,setMobileOpen]=useState(false);
 const scrollTo=(id)=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setMobileOpen(false)};
 return <div className="min-h-screen overflow-x-hidden bg-slate-50 text-slate-900">
  <header className="fixed inset-x-0 top-0 z-50 border-b border-white/20 bg-slate-950/80 text-white shadow-lg backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8">
   <button onClick={()=>scrollTo('home')} className="group flex items-center gap-3 text-left"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-indigo-500 to-sky-500 shadow-lg shadow-indigo-500/30 transition-transform group-hover:scale-105"><Sparkles size={21}/></span><span><span className="block text-xl font-extrabold tracking-tight">SXOPOP</span><span className="block text-[10px] font-medium tracking-[0.18em] text-slate-300">Intelligent Hub</span></span></button>
   <nav className="hidden items-center gap-8 md:flex">{navItems.map(([label,id])=><button key={id} onClick={()=>scrollTo(id)} className="text-sm font-medium text-slate-300 transition hover:text-white">{label}</button>)}</nav>
   <div className="hidden items-center gap-3 md:flex"><button onClick={()=>scrollTo('pricing')} className="rounded-xl border border-white/20 px-5 py-2.5 text-sm font-semibold transition hover:border-white/50 hover:bg-white/10">Log In</button><button onClick={()=>scrollTo('pricing')} className="rounded-xl bg-white px-5 py-2.5 text-sm font-bold text-indigo-700 shadow-lg transition hover:-translate-y-0.5 hover:bg-slate-100">Try Free</button></div>
   <button aria-label="Open menu" onClick={()=>setMobileOpen(!mobileOpen)} className="rounded-xl border border-white/15 p-2 md:hidden">{mobileOpen?<X/>:<Menu/>}</button></div>
   {mobileOpen&&<div className="border-t border-white/10 bg-slate-950 px-5 py-5 md:hidden"><div className="flex flex-col gap-2">{navItems.map(([label,id])=><button key={id} onClick={()=>scrollTo(id)} className="rounded-xl px-4 py-3 text-left text-sm text-slate-200 hover:bg-white/10">{label}</button>)}<div className="mt-2 grid grid-cols-2 gap-2"><button onClick={()=>scrollTo('pricing')} className="rounded-xl border border-white/20 py-3 text-sm font-semibold">Log In</button><button onClick={()=>scrollTo('pricing')} className="rounded-xl bg-white py-3 text-sm font-bold text-indigo-700">Try Free</button></div></div></div>}
  </header>
  <main><section id="home" className="relative flex min-h-[760px] items-center overflow-hidden bg-gradient-to-br from-indigo-600 via-indigo-500 to-sky-500 pt-20 text-white"><div className="absolute inset-0 opacity-20 [background-image:linear-gradient(rgba(255,255,255,.15)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.15)_1px,transparent_1px)] [background-size:48px_48px]"/><motion.div animate={{y:[0,-18,0],x:[0,12,0]}} transition={{duration:8,repeat:Infinity,ease:'easeInOut'}} className="absolute -right-28 top-32 h-80 w-80 rounded-full bg-sky-300/25 blur-3xl"/><motion.div animate={{y:[0,20,0]}} transition={{duration:10,repeat:Infinity,ease:'easeInOut'}} className="absolute -left-32 bottom-0 h-96 w-96 rounded-full bg-indigo-900/20 blur-3xl"/>
   <div className="relative mx-auto grid max-w-7xl items-center gap-14 px-5 py-24 sm:px-8 lg:grid-cols-[1.1fr_.9fr]"><motion.div initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{duration:.7}}><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-white/25 bg-white/10 px-4 py-2 text-xs font-semibold backdrop-blur"><Sparkles size={14}/> Intelligent digital ecosystem</div><div className="mb-8 text-4xl font-black tracking-tight sm:text-6xl"><span className="block">SXOPOP</span><span className="mt-1 block text-white/90">Intelligent Hub</span></div><h1 className="font-myanmar text-2xl font-bold leading-relaxed sm:text-3xl">ဉာဏ်ရည်ထက်မြက်သော ဗဟိုစနစ်</h1><p className="mt-6 max-w-2xl text-base leading-8 text-indigo-50 sm:text-lg">တစ်နေရာတည်းကနေ သင့်ရဲ့ content, templates နဲ့ digital presence ကို ပိုမိုလွယ်ကူမြန်ဆန်စွာ စီမံခန့်ခွဲနိုင်တဲ့ modern intelligent hub.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><button onClick={()=>scrollTo('pricing')} className="group inline-flex items-center justify-center gap-2 rounded-2xl bg-white px-7 py-4 font-bold text-indigo-700 shadow-2xl transition hover:-translate-y-1">အခမဲ့ စမ်းသုံးပါ <ArrowRight size={18} className="transition group-hover:translate-x-1"/></button><button onClick={()=>scrollTo('demo')} className="inline-flex items-center justify-center gap-2 rounded-2xl border border-white/30 bg-white/10 px-7 py-4 font-bold backdrop-blur transition hover:bg-white/20"><Play size={17}/> နမူနာ ကြည့်ပါ</button></div></motion.div>
   <motion.div initial={{opacity:0,scale:.94}} animate={{opacity:1,scale:1}} transition={{duration:.8,delay:.15}}><div className="rounded-[2rem] border border-white/25 bg-white/10 p-3 shadow-2xl backdrop-blur-xl"><div className="rounded-[1.5rem] bg-slate-950/90 p-5"><div className="mb-5 flex items-center justify-between"><div className="flex gap-1.5"><i className="h-2.5 w-2.5 rounded-full bg-red-400"/><i className="h-2.5 w-2.5 rounded-full bg-amber-400"/><i className="h-2.5 w-2.5 rounded-full bg-emerald-400"/></div><span className="text-[10px] text-slate-500">SXOPOP / Dashboard</span></div><div className="grid grid-cols-3 gap-3">{[['Users','12.8K','+18%'],['Posts','48.2K','+24%'],['Reach','1.9M','+31%']].map(([a,b,c])=><div key={a} className="rounded-2xl bg-white/[.06] p-4"><p className="text-[10px] text-slate-400">{a}</p><p className="mt-2 text-xl font-bold">{b}</p><p className="mt-1 text-[10px] text-emerald-400">{c}</p></div>)}</div><div className="mt-3 rounded-2xl bg-white/[.06] p-4"><div className="mb-5 flex justify-between text-xs"><span className="text-slate-300">Performance</span><span className="text-indigo-300">98.6%</span></div><div className="flex h-32 items-end gap-2">{[38,55,48,67,60,80,72,92,85,100,88,96].map((h,i)=><div key={i} className="flex-1 rounded-t-md bg-gradient-to-t from-indigo-600 to-sky-400 opacity-80" style={{height:`${h}%`}}/>)}</div></div></div></div></motion.div></div></section><Features/><Templates/><Pricing/><Payment/><section id="demo" className="bg-slate-950 px-5 py-24 text-white sm:px-8"><div className="mx-auto max-w-5xl text-center"><div className="mx-auto mb-6 grid h-16 w-16 place-items-center rounded-2xl bg-indigo-500/15 text-indigo-300"><Code2/></div><h2 className="font-myanmar text-3xl font-black sm:text-4xl">SXOPOP ကို လက်တွေ့ စမ်းကြည့်ပါ</h2><p className="mx-auto mt-5 max-w-2xl font-myanmar leading-8 text-slate-400">သင့် digital workflow ကို ပိုရိုးရှင်းစေမယ့် Intelligent Hub အတွေ့အကြုံကို စတင်ပါ။</p><button onClick={()=>scrollTo('pricing')} className="mt-8 inline-flex items-center gap-2 rounded-2xl bg-gradient-to-r from-indigo-500 to-sky-500 px-7 py-4 font-bold shadow-xl transition hover:-translate-y-1">အခမဲ့ စတင်မယ် <ChevronRight size={18}/></button></div></section></main><Footer/></div>;
}
